### ISSUE TITLE
Current usage of webextension-polyfill pollutes global scope

### ISSUE THREAD

**Issue by olso-nordsec** [SimplifyJobs/webpack-ext-reloader#233] opened 2022-03-29 15:38 UTC
[//]: # (These comments will not show up. You can keep them or delete them, up to you.)

#### Describe the bug

[//]: # (A clear and concise description of what the bug is.)

In our project we are already using `webextension-polyfill` (via UMD).

This project uses https://github.com/SimplifyJobs/webpack-ext-reloader/blob/master/src/middleware/middleware-source-builder.ts#L16 which will pollute global scope

#### Error Stacks

```bash
put error stacks here
```

#### To Reproduce

Try to use `webextension-polyfill` (as UMD) and `webpack-ext-reloader` at the same time

##### Config

```javscript
add your webpack config here
```

##### Example

[//]: # (A minimal example to reproduce the behavior if relevant.)

#### Expected behavior

[//]: # (A clear and concise description of what you expected to happen.)

Usage of `webextension-polyfill` within this project should not pollute global scope. It should be imported as a module.

#### Environment:

- OS:
- Browser Version:
- webpack Version:
- webpack-ext-reloader Version:

#### I'm going to open a PR

- [ ] yes
- [ ] no
- [x] maybe

#### Additional information

[//]: # (Add any addittional infomration about the bug/problem here.)

**Comment by rushilsrivastava** [comment] 2022-03-29 18:10
Can you provide a minimal example of your case? The reason this is injected is so that it works for all webext supported-browsers without having to use the polyfill (i.e. if you are only targeting one browser anyways). We use it internally with `webextension-polyfill` and haven't had any issues.

**Comment by sherifmayika** [comment] 2022-11-28 16:59
webextension-polyfill is useless in MV3 
kindly remove it.
https://stackoverflow.com/questions/68488195/browser-extension-manifest-v3-with-webextension-polyfill-does-not-allow-browser

**Comment by vialoh** [comment] 2023-09-28 17:27
I looked into this and without a reproducible example, I'm not sure of the best way to fix it. I'm closing this for now but if you can provide an example for me to go by (or ideally create a PR with the fix yourself), I will reopen.

**Closed by vialoh** 2023-09-28 17:27 UTC
Labels: type: bug
